import AuthProvider from "@/providers/AuthProvider";
import "./globals.scss";
import type { Metadata } from "next";
import MobileMenu from "@/components/MobileMenu";
import Header from "@/components/Header";
import FooterMenu from "@/components/FooterMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {/* <MobileMenu/> */}
          {/* <Header/> */}
          <div className="children">{children}</div>
          <FooterMenu />
        </AuthProvider>
      </body>
    </html>
  );
}
